#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 13 14:27:08 2017

@author: ad8
"""

import os
path = '/rfanfs/pnl-zorro/home/akti/aristotle/corr'
for root, dirs, files in os.walk(path):
    for name in files:
        if name.startswith(("S")) and name.startswith(("Ed.nhdr")):
            print name
